collections:
  articles:
    output: true
    permalink: /:collection/:name
  pages:
    output: true
    permalink: /:name
  tags:
    output: true
    permalink: /:name

defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "standard-post"
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tagpage"
  - scope:
      path: ""
    values:
      layout: "default"

port: 4000
host: 127.0.0.1
